---
- name: install build-essential
  apt:
    name: build-essential
    state: present

- name: install libssl-dev
  apt:
    name: libssl-dev
    state: present

- name: download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh
    dest: /home/vagrant/install_nvm.sh

- name: install nvm
  shell: sh /home/vagrant/install_nvm.sh