- name: install apt-transport-https
  apt: 
    name: apt-transport-https
    state: present

- name: install ca-certificates
  apt: 
    name: ca-certificates
    state: present

- name: install curl
  apt: 
    name: curl
    state: present

- name: install software-properties-common
  apt: 
    name: software-properties-common
    state: present

- name: add docker apt-key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: apt update
  apt: 
    update_cache: yes

- name: install docker-engine
  apt:
    name: docker-engine
    state: present

- name: create docker mongo shared folder
  file:
    path: /home/vagrant/dev/docker/mongo
    state: directory
    mode: 0755
  become: false

- name: install pip
  apt:
    name: python-pip
    state: present

- name: install docker-py
  pip:
    name: docker-py

- name: docker pull mongo image
  docker_image:
    name: mongo:3.0

- name: docker pull redis image
  docker_image:
    name: redis

- name: configure mongo docker
  docker:
    name: mongo-dev
    image: mongo:3.0
    state: present
    ports:
      - 27017:27017
    volumes:
    - /home/vagrant/dev/docker/mongo:/shared

- name: configure redis docker
  docker:
    name: redis-dev
    image: redis
    state: present
    ports:
      - 6379:6379
