- name: install apt-transport-https
  apt: 
    name: apt-transport-https
    state: present

- name: install ca-certificates
  apt: 
    name: ca-certificates
    state: present

- name: install curl
  apt: 
    name: curl
    state: present

- name: install software-properties-common
  apt: 
    name: software-properties-common
    state: present

- name: add docker apt-key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: apt update
  apt: 
    update_cache: yes

- name: install docker-engine
  apt:
    name: docker-engine
    state: present
